// Code generated by tygo / manual translation. DO NOT EDIT.

export interface User {
  id: number;
  created_at: string;
  updated_at: string;
  full_name: string;
  username: string;
  picture: string;
  email: string;
  role: string; // "admin", "viewer", "billing"
}

export interface FamilyLink {
  id: number;
  created_at: string;
  sponsor_id: number;
  subject_id: number;
  relation: string;     // e.g. "Father", "Mother"
  access_role: string;  // e.g. "admin", "viewer"
}

export interface VitalTelemetry {
  id: number;
  subject_id: number;
  vital_type: string; // e.g. "blood_pressure", "blood_glucose"
  value_metric: number;
  value_unit: string; // e.g. "mmHg", "mg/dL"
  context_data: string; // JSON metadata holding secondary telemetry parameters
  recorded_at: string;
}

export interface EmergencyQR {
  id: number;
  subject_id: number;
  qr_hash: string;
  blood_group: string;
  allergies: string;
  active_meds: string;
  sponsor_phone: string;
  is_active: boolean;
}
